- type: job
  id: Commander
  name: Командир
  description: Глава штурмовой группы "Жнецы"
  playTimeTracker: JobCommander
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1 # 48 hours
  whitelisted: true
  access:
  - SyndicateAgent
  - NuclearOperative
  startingGear: CommanderGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconCommander"
  supervisors: job-supervisors-nobody
  weight: 40
  displayWeight: 40
  setPreference: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - NFSyndicate
  - !type:AddImplantSpecial
    implants: [ DeathRattleImplanter ]

- type: startingGear
  id: CommanderGear
  equipment:
    ears: ClothingHeadsetAltSyndicate
    id: SyndiPDAComa
    belt: ClothingBeltSheathSyndicateFilled
    pocket1: NFWeaponPistolCobra
    mask: ClothingMaskGasSwat
  storage:
    back:
    - NFBoxSurvivalExtended
    - NFMagazinePistol45
    - SyndicateDataMinerFlatpack

- type: chameleonOutfit
  id: CommanderChameleonOutfit
  job: Commander
